<header>

    <nav>
        <img src="{{ Vite::asset('resources/img/dc-logo.png') }}" alt="DC Logo">
        <ul>
            <li>
                <a>characters</a>
            </li>
            <li>
                <a>comics</a>
            </li>
            <li>
                <a>movies</a>
            </li>
            <li>
                <a>tv</a>
            </li>
            <li>
                <a>games</a>
            </li>
            <li>
                <a>collectibles</a>
            </li>
            <li>
                <a>videos</a>
            </li>
            <li>
                <a>fans</a>
            </li>
            <li>
                <a>news</a>
            </li>
            <li>
                <a>shop</a>
            </li>
        </ul>
    </nav>

</header>